name: NYCgaby
favicon: null
layout_spectrum: 0.49903
typography_spectrum: 0.9461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1012'
    - '#8d9192'
    - '#b2b4af'
    - '#fddcad'
    - '#645d55'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
