name: NYCgaby
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9930580446962267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1012'
    - '#8d9192'
    - '#b2b4af'
    - '#fddcad'
    - '#645d55'
  brandStrength: 0.1875
  lightness: 0.29697781382128596
  saturation: 0.5173579398542643
  rhythmicContrast: 0.6055261332076043
purpose: []
